# ~/.config/bottom/bottom.toml

[colors]
# The main background and text
table_header_color = "#458588" # Blue
all_cpu_color = "#cc241d"      # Red
avg_cpu_color = "#b16286"      # Purple
cpu_core_colors = ["#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#689d6a"]
ram_color = "#98971a"          # Green
cache_color = "#076678"        # Aqua
swap_color = "#d79921"         # Yellow
rx_color = "#98971a"           # Green
tx_color = "#cc241d"           # Red
border_color = "#ebdbb2"       # Surface/Light Grey
highlighted_border_color = "#458588" # Blue
text_color = "#3c3836"         # Dark Text
selected_text_color = "#fbf1c7" # Background color for contrast
selected_bg_color = "#076678"   # Blue highlight
graph_color = "#928374"        # Grey
